### ISSUE TITLE
27-inch, Late 2013 iMac - brightness not working as expected

### ISSUE THREAD

**Issue by agileadam** [kfix/ddcctl#10]
Adjusting the brightness of my mac isn't working as expected.

Using `ddcctl -d 1 -b ?` to query the brightness, if I use my function keys to set brightness:

(notch = little square on the overlay graphic when you use the function keys to set brightness)

notch 0 = current: 16, max: 255  (lowest)
notch 1 = current: 138, max: 255
notch 2 = current: 127, max: 255
notch 3 = current: 72, max: 255
notch 4 = current: 255, max: 255
notch 5 = current: 32, max: 255
...
last notch = current: 182, max: 255 (brightest)

When I try to set the brightness, no matter what value I pass, it always results in the same level (approximately 70% of full brightness if I had to guess). If I use function keys to increase to 100% and then set brightness to X, it'll go to about 70%. If I use function keys to decrease to 0% and then set brightness to X, it'll go to about 70%.

It's no big deal if you can't spend time looking at this, but maybe you know what's up.

Thanks again!

**Comment by kfix** [comment]
@agileadam, the DDC standard is very loosely implemented by monitor manufacturers beyond sleeping the display.
only Apple ships an OS that auto-adjusts brightness (only for its own displays) and it uses the USB bus to do that, not DDC!
I can't remotely debug your weird monitor, sorry!

**Comment by agileadam** [comment]
No problem. Thanks for responding.
