### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by jamesstidard** [kfix/ddcctl#100]
Hi,

I was wondering how this project is licensed? I'm looking to see if I could use it and bundle it with my own side project I'm working on, so the user (probably just me) doesn't need to install it separately.

Thanks,
James

EDIT:
To maybe start answering my own question. The credited source for this project is https://github.com/jontaylor/DDC-CI-Tools-for-OS-X which is under a GPL 3.0 licence. Presumably this project would inherit that same licence.

**Comment by kfix** [comment]
IANAL but that is my interpretation of the situation as well

**Comment by kfix** [comment]
the Obj-C part of the program derived from "DDC Panel" fro the forms was licensed thusly:
```
//  AppDelegate.m
//  DDC Panel
//
//  Created by PHPdev32 on 2/19/13.
//  Licensed under GPLv3, full text at http://www.gnu.org/licenses/gpl-3.0.txt
//
```

I'll add a LICENSE file to that effect for the whole thing, although its a bit muddy since there have been a few contribs in between.
