### ISSUE TITLE
External HDMI monitors detected intermittently on MacBook Pro

### ISSUE THREAD

**Issue by dfaulkner** [kfix/ddcctl#101]
2019 MacBook Pro with a pair of identical HP external monitors (HP EliteDisplay E232), connected to my MacBook via HDMI, via a couple of adapters:

Display 1: j5 create JCA374 USB-C Multi-Adapter - HDMI/Ethernet/USB 3.1 HUB/PD 2.0
Display 2: Satechi ST-TCPHEM Type-C Pro Hub adapter with ethernet

I'm able to use ddccdl to talk to the monitors some times, but not always.
My Primary use case is to change the input. When ddcctl detects the monitors, this works every time: I can switch to DisplayPort (-i 15)  or to HDMI (-i 17), regardless of which of the two inputs the monitors are on when I start.

More than half of the time, ddcctl just doesn't see the monitors. It will inform me "I: found 0 external display" and exit.
I can't seem to find a circumstance that makes a difference between detecting the monitors and not detecting the monitors.

Here is the identity string output by ddccdl (when it works):

```
D: CGDisplay 322CF4A4-C269-47E3-F73B-5D22546B519B dispID(#1007459975) (1920x1080 0°) 96.00 DPI
D: CGDisplay 6A52D817-B425-9CE8-AACD-EBE0F7D587DF dispID(#1007459977) (1920x1080 0°) 96.00 DPI
I: found 2 external displays
I: polling EDID for #1 (ID 1007459975 => IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/ATY,Palena@1/AMDFramebufferVIB)
I: got edid.name: HP E232
I: polling EDID for #2 (ID 1007459977 => IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/ATY,Palena@3/AMDFramebufferVIB)
I: got edid.name: HP E232
```

**Comment by adams-family** [comment]
I had a similar problem with a docking station (MacBook -> Thunderbolt -> Docking Station -> DisplayPort -> Display). In 19 cases out of 20 everything was working fine, then I just couldn't control the monitor via `ddcctl` until restart.

I simply returned the docking station and never had a problem ever since, not a single one. I know it might not solve your issue, just FYI.

**Comment by dfaulkner** [comment]
Absent the dock, how are you converting Thunderbolt to your external display?
I'll try to find a higher quality dock/adapter, but that will take a while.

**Comment by adams-family** [comment]
I'm using this guy: (I wanted a direct laptop-display cable instead of a cable + an adapter)

https://www.digitec.ch/de/s1/product/j5create-usb-30-type-c-to-4k-displayport-120m-display-port-usb-c-video-kabel-9894364

**Comment by dfaulkner** [comment]
I'm closing my original issue. After reporting this, I discovered my MacBook had hardware issues with its main logic board. After the repair, everything seems to work just fine.
