### ISSUE TITLE
Silly question - is there anything in 10.14 that would prevent IOI2CSendRequests from going through?

### ISSUE THREAD

**Issue by pavelmalik** [kfix/ddcctl#105]
I seem to be getting return value of 64 on IOI2CRequest->result for IOI2CSendRequests to set brightness/power etc. What's the usual procedure for debuggin this type of stuff?

Edit:
Looks like I'm getting 0x0040 error code, doesn't look like there's much documentation for it:
https://www.osstatus.com/search/results?platform=all&framework=all&search=0x0040

**Comment by kfix** [comment]
I'd have suggested `make debug` which makes it print more stuff.

but it looks like that target was broken - maybe the Xcode debug build still works :-/

**Comment by kfix** [comment]
I'm gonna close for lack of info, but feel free to reopen if you find something out.
