### ISSUE TITLE
[REQUEST] DDM KVM controls

### ISSUE THREAD

**Issue by Sparagmos** [kfix/ddcctl#106]
On Windows there is a 'Switch USB' button on the 'Input Manager' tab of DDM. This acts as a KVM button. I can't figure out the ddm.exe command/argument for it, but you can set a keybinding for it. It would be nice to have it on the mac side so you could switch your KB/M back to a windows machine.

**Comment by kfix** [comment]
There are tools on Mac to monitor keyboard sequences and execute arbitrary commands, such as `ddcctl`.
I listed some in the README:
> You can point Alfred, ControlPlane, or Karabiner at it to quickly switch presets.
