### ISSUE TITLE
can't increase/decrease brightness

### ISSUE THREAD

**Issue by luistrong** [kfix/ddcctl#107]
ddcctl -d 1 -b 10+

D: action: b: 10+
D: querying VCP control: #16 =?
E: No data after 10 tries! (1ns reply-timeout)
E: DDC send command failed!
E: VCP control #16 (0x10) = current: 0, max: 0
D: relative setting: 0 + 10 = 0 (clamped to 0, 0)
D: setting VCP control #16 => 0

it seem it can't find the current brightness of the display

**Comment by Bubba14** [comment]
I have the same issue 

![Screen Shot 2021-06-26 at 10 42 21 AM](https://user-images.githubusercontent.com/85909099/123518379-3e4cd700-d66b-11eb-9ed2-00168e7e414b.png)

**Comment by kfix** [comment]
Unable to debug, insufficient info
