### ISSUE TITLE
Macbook Air M1 - INPUT CHANGE ERROR

### ISSUE THREAD

**Issue by vgdss** [kfix/ddcctl#114]
I have a macbook air m1 and use it with an external monitor AG251F1WG2 on the HDMI2 input. On that monitor, my desktop with Windows 10 is also connected to the Display Port input. The idea is to keep changing between HDMI2 and DP (-i 15 or -i 18), but I ended up running into this error below: 

❯ ddcctl -d 1 -i 18
D: CGDisplay 71C6C731-8247-B410-0857-D6964E3302DB dispID(#2) (1920x1080 0°) 90.00 DPI
I: found 1 external display
E: Failed to parse WindowServer's preferences! (/Library/Preferences/com.apple.windowserver.plist)
E: Failed to acquire framebuffer device for display

**Comment by kfix** [comment]
Does not work on M1s yet, refer to #86 
is also on the project list  @ https://github.com/kfix/ddcctl/projects/1

**Comment by bareblackfoot** [comment]
It's been two years. It still doesn't work?

**Comment by kfix** [comment]
yep, 2 years and not one contribution from anybody to do this. isn't open source great!

**Comment by owens-ben** [comment]
hello?

**Comment by nuddler** [comment]
Any progress here?
