### ISSUE TITLE
ASUS VG27A is not supported for input switch

### ISSUE THREAD

**Issue by hawktang** [kfix/ddcctl#120]
Sorry, it might due to the apdator. Let me make it sure first.

For MAC USB C to monitor USB C, it might be considered as directly connection. But for MAC USB C -Adaptor-Monitor HDMI, it might not. EDID might be acquired, but DDC might not working.

Sending just an error message is not enough!  
Requirements for submitters
--
ASUS VG27A is not supported for input switch

❯ ddcctl -d 2 -i 15
D: CGDisplay DB881D8F-C5B9-E8DC-672F-5DBD34B9B136 dispID(#724074325) (3840x2160 0°) 140.00 DPI
D: CGDisplay 727BAA63-5C96-B7A0-D356-E0ED22A0327C dispID(#751421642) (2560x1440 0°) 109.00 DPI
I: found 2 external displays
I: polling EDID for #2 (ID 751421642 => IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/ATY,Longavi@4/AMDFramebufferVIB)
I: got edid.name: VG27A
I: got edid.serial: KALMQS178417
D: action: i: 15
D: setting VCP control #96 => 15

But Dell U3219Q is working

❯ ddcctl -d 1 -i 15
D: CGDisplay DB881D8F-C5B9-E8DC-672F-5DBD34B9B136 dispID(#724074325) (3840x2160 0°) 140.00 DPI
D: CGDisplay DDE42992-8FDF-FB6A-8D7F-9C03AF9831D5 dispID(#751421642) (2560x1440 0°) 109.00 DPI
I: found 2 external displays
I: polling EDID for #1 (ID 724074325 => IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/ATY,Longavi@3/AMDFramebufferVIB)
I: got edid.serial: 5N7N413
I: got edid.name: DELL U3219Q
D: action: i: 15
D: setting VCP control #96 => 15

Both Dell U3219Q and ASUS VG27A are working in Windows with ClickMonitorDDC

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	447.40.12.0.0
  OS Loader Version:	540.40.4~45
  SMC Version (system):	2.45f5

Errors are a warning for you (the unknown monitor & Mac owner) and  
do not in-and-of-themselves mean there is a bug in `ddcctl`.

You must include pertinent information on your monitors, Macintosh, and macOS, or else  
your issue will get an `incomplete` tag.

Making & running a debug build (`make debug`) and reproducing your issue to provide  
detailed output for the report is highly encouraged!  

Known issues
--
I _will_ close reports about these issues out-of-hand:  

### __MY HACKINTOSH <whatever>__:  
You're on your own with Hackintoshes.  

### __YOUR MONITOR MAY NOT CORRECTLY SUPPORT MUCH OF DDC__  
The DDC standard is very loosely implemented by monitor manufacturers beyond sleeping the display.  
* This is because Windows doesn't use brightness sensors to dim screens like OSX does —via USB, not DDC!
* Adjusting brightness, contrast, and super-awesome-multimedia-frobber-mode may not be possible.  

### __YOUR MONITOR MIGHT FREEZE__ when making settings, especially the non-brightness/contrast ones.  
* Power cycle the monitor.  
* You just have to trial-and-error what works for your hardware.  

Practical advice
--
VGA cables seem to wreak havoc with DDC comms.  
Use DVI/DisplayPort/Thunderbolt if you can.

Please consider that there is no team working on `ddcctl`, it is a fun-time project  
that has long-since been considered "finished".  

Bad, incomplete, or *lazy* reports and non-bugs are not fun to work on  
so I *will* be cranky towards their reporters who didn't heed these instructions.

**Comment by kfix** [comment]
i'm going to close this one as its not actionable.

Thinking about opening up the "discussions" github feature so that general troubleshooting can be worked out from those, might want to ping back there if you still need help.
