### ISSUE TITLE
mostly thanks

### ISSUE THREAD

**Issue by iwelch** [kfix/ddcctl#13]
not really an issue.  just a thanks from here.  works like a charm on a Dell 2715q.

minor compile warnings.  can be ignored.

perhaps mention a typical use in the readme.md?

`  # ddcctl -b 1 -d 1
`

**Comment by kfix** [comment]
Every manufacturers' brightness & contrast scales are different... I don't want to make any suggestions except to cautiously experiment.
Thanks for the note!
