### ISSUE TITLE
Read problems with P2415Q

### ISSUE THREAD

**Issue by jacobseptember** [kfix/ddcctl#14]
I'll start a new issue for this, to see if there are any suggestions.

OS X 10.11.2, hackintosh, GTX 960, web driver 346.03.04f02. I suppose I can update to latest OS X/web driver if you think that might help.

Simple brightness writes are fine.

Brightness query results in:
> 06:48.454 ddcctl[875:32303] D: command arg-pair: b: ?
> 06:48.454 ddcctl[875:32303] D: querying VCP control: #16 =?
> 06:58.931 ddcctl[875:32303] E: DDC send command failed!
> 06:58.931 ddcctl[875:32303] E: VCP control #16 = current: 0, max: 0

and the display freezes immediately after the "querying" line. Both displays freeze, in fact. Note that the timestamps indicate the error lines only appear after I power down the affected monitor. Power-cycling the unaffected monitor has no effect.

Similarly for relative changes:
> 09:14.194 ddcctl[970:36261] D: command arg-pair: b: 30+
> 09:14.194 ddcctl[970:36261] D: querying VCP control: #16 =?
> 09:18.419 ddcctl[970:36261] E: DDC send command failed!
> 09:18.419 ddcctl[970:36261] E: VCP control #16 = current: 0, max: 0
> 09:18.419 ddcctl[970:36261] D: relative setting: 0 + 30 = 30
> 09:18.419 ddcctl[970:36261] D: setting VCP control #16 => 30
> 09:18.934 ddcctl[970:36261] E: Failed to send DDC command!

Again, note the timestamps.

Now, with a wait of 0.3 sec, brightness is not read correctly, but at least the display doesn't freeze:
> 14:48.944 ddcctl[1101:45318] D: command arg-pair: w: 300000
> 14:48.944 ddcctl[1101:45318] D: command arg-pair: b: 50+
> 14:48.944 ddcctl[1101:45318] D: querying VCP control: #16 =?
> 14:49.046 ddcctl[1101:45318] E: DDC send command failed!
> 14:49.046 ddcctl[1101:45318] E: VCP control #16 = current: 0, max: 0
> 14:49.047 ddcctl[1101:45318] D: relative setting: 0 + 50 = 50
> 14:49.347 ddcctl[1101:45318] D: setting VCP control #16 => 50

With a wait of 1 sec, the brightness is read correctly (sort of: my suspicion is that the monitor does not properly implement the "value changed" function, so ddcctl "reads" the last software-set value, rather than the current value, set by OSD or software).
> 17:24.445 ddcctl[1106:48548] D: command arg-pair: w: 1000000
> 17:24.445 ddcctl[1106:48548] D: command arg-pair: b: 30+
> 17:24.445 ddcctl[1106:48548] D: querying VCP control: #16 =?
> 17:24.547 ddcctl[1106:48548] I: VCP control #16 = current: 20, max: 100
> 17:24.547 ddcctl[1106:48548] D: relative setting: 20 + 30 = 50
> 17:25.548 ddcctl[1106:48548] D: setting VCP control #16 => 50

But even so, the supposed "setting VCP control #16" doesn't happen. The monitor stays at its original brightness.

Now trying much longer wait times (4 sec, 5 sec), on one occasion I got a correct read w/o freeze and on one occasion I got a correct read w/o freeze (but no correct set). Mostly I just got freezes again.

Setting the wait to 15 seconds got better results on the freezes (none, the whole two times I tested it), but still to go on actually setting the final brightness.

Thoughts?

**Comment by jacobseptember** [comment]
Playing around with it a bit more this morning, it seems the problem lies somewhere in the fact that I'm using DisplayPort to connect to the monitor. Specifically, DP at the graphics card, mDP at the monitor.

If I use HDMI, there is no problem reading values from the monitor and there is no freezing. In fact, if I connect the monitor using **both** DP and HDMI, I can look at the DP output (ddcctl: "display 1") while controlling the HDMI output (ddcctl: "display 3"), and the monitor changes brightness precisely as desired.

This is annoying.

**Comment by swrobel** [comment]
Working fine for me here. iMac 27" Late 2012 (AMD Radeon R9 M380), MacOS 10.12 PB4, P2415Q secondary monitor hooked up via mini-dp to mini-dp cable

```
$ ddcctl -d 2 -b \? -c \?
2016-08-15 13:35:15.844 ddcctl[94339:6881113] D: NSScreen #69935852 (2560x1440) DPI is 108.50
2016-08-15 13:35:15.845 ddcctl[94339:6881113] D: NSScreen #724049360 (1080x1920) DPI is 92.50
2016-08-15 13:35:15.845 ddcctl[94339:6881113] I: found 2 displays
2016-08-15 13:35:15.845 ddcctl[94339:6881113] I: polling display 2's EDID
2016-08-15 13:35:15.854 ddcctl[94339:6881113] I: got edid.serial: XXXXXXXXX
2016-08-15 13:35:15.854 ddcctl[94339:6881113] I: got edid.name: DELL P2415Q
2016-08-15 13:35:15.855 ddcctl[94339:6881113] D: command arg-pair: d: 2
2016-08-15 13:35:15.855 ddcctl[94339:6881113] D: command arg-pair: b: ?
2016-08-15 13:35:15.855 ddcctl[94339:6881113] D: querying VCP control: #16 =?
2016-08-15 13:35:15.959 ddcctl[94339:6881113] I: VCP control #16 = current: 60, max: 100
2016-08-15 13:35:15.959 ddcctl[94339:6881113] D: command arg-pair: c: ?
2016-08-15 13:35:15.959 ddcctl[94339:6881113] D: querying VCP control: #18 =?
2016-08-15 13:35:16.063 ddcctl[94339:6881113] I: VCP control #18 = current: 75, max: 100
```

**Comment by deseven** [comment]
I have exactly the same problem but on MacBook Pro (Retina, 15-inch, Late 2013) with Sierra.  
So this is not hackintosh-specific. Any ideas?

**Comment by jacobseptember** [comment]
Ha, good to know. Is it what I had—non-functional VCP #16, display freezing?

**Comment by kfix** [comment]
Can you `dtruss ddcctl -b ?`

**Comment by deseven** [comment]
Sure.
I did `sudo dtruss ddctl -d 1 -b \?` and [here is the output](http://eri.deseven.info/share/ddcctl.txt).

**Comment by deseven** [comment]
I don't know what exactly i did, but after many experiments contrast setting also started to work.
Still no luck with value reading or input selection.

**Comment by kfix** [comment]
Try a debug build, which prints more information
`make debug`

**Comment by deseven** [comment]
```
2017-04-23 14:19:59.255 ddcctl[9710:1882694] D: NSScreen #724049871 (1920x1080 0°) HiDPI
2017-04-23 14:19:59.255 ddcctl[9710:1882694] I: found 1 external display
2017-04-23 14:19:59.255 ddcctl[9710:1882694] I: polling display 1's EDID

Framebuffer: NVDA
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/P0P2@1/IOPP/GFX0@0/NVDA,Display-B@1/NVDA/display0/AppleDisplay
VN:4268 PN:41150 SN:809906252 UN:3 IN:15619 Serial:

2017-04-23 14:19:59.268 ddcctl[9710:1882694] I: got edid.serial: D8VXF6AO0F0L
2017-04-23 14:19:59.268 ddcctl[9710:1882694] I: got edid.name: DELL P2415Q
2017-04-23 14:19:59.268 ddcctl[9710:1882694] D: action: b: ?
2017-04-23 14:19:59.268 ddcctl[9710:1882694] D: querying VCP control: #16 =?

D: IOI2CTransactionTypes: 0x1f (31)
D: IOI2CNoTransactionType                   supported
D: IOI2CSimpleTransactionType               supported
D: IOI2CDDCciReplyTransactionType           supported
D: IOI2CCombinedTransactionType             supported
D: IOI2CDisplayPortNativeTransactionType    supported

Framebuffer: NVDA
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/P0P2@1/IOPP/GFX0@0/NVDA,Display-B@1/NVDA/display0/AppleDisplay
VN:4268 PN:41150 SN:809906252 UN:3 IN:16187 Serial:


D: IOI2CTransactionTypes: 0x1f (31)
D: IOI2CNoTransactionType                   supported
D: IOI2CSimpleTransactionType               supported
D: IOI2CDDCciReplyTransactionType           supported
D: IOI2CCombinedTransactionType             supported
D: IOI2CDisplayPortNativeTransactionType    supported

Framebuffer: NVDA
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/P0P2@1/IOPP/GFX0@0/NVDA,Display-B@1/NVDA/display0/AppleDisplay
VN:4268 PN:41150 SN:809906252 UN:3 IN:16939 Serial:


D: IOI2CTransactionTypes: 0x1f (31)
D: IOI2CNoTransactionType                   supported
D: IOI2CSimpleTransactionType               supported
D: IOI2CDDCciReplyTransactionType           supported
D: IOI2CCombinedTransactionType             supported
D: IOI2CDisplayPortNativeTransactionType    supported

D: IOI2CTransactionTypes: 0x1f (31)
D: IOI2CNoTransactionType                   supported
D: IOI2CSimpleTransactionType               supported
D: IOI2CDDCciReplyTransactionType           supported
D: IOI2CCombinedTransactionType             supported
D: IOI2CDisplayPortNativeTransactionType    supported

D: IOI2CTransactionTypes: 0x1f (31)
D: IOI2CNoTransactionType                   supported
D: IOI2CSimpleTransactionType               supported
D: IOI2CDDCciReplyTransactionType           supported
D: IOI2CCombinedTransactionType             supported
D: IOI2CDisplayPortNativeTransactionType    supported

D: IOI2CTransactionTypes: 0x1f (31)
D: IOI2CNoTransactionType                   supported
D: IOI2CSimpleTransactionType               supported
D: IOI2CDDCciReplyTransactionType           supported
D: IOI2CCombinedTransactionType             supported
D: IOI2CDisplayPortNativeTransactionType    supported

D: IOI2CTransactionTypes: 0x1f (31)
D: IOI2CNoTransactionType                   supported
D: IOI2CSimpleTransactionType               supported
D: IOI2CDDCciReplyTransactionType           supported
D: IOI2CCombinedTransactionType             supported
D: IOI2CDisplayPortNativeTransactionType    supported

D: IOI2CTransactionTypes: 0x1f (31)
D: IOI2CNoTransactionType                   supported
D: IOI2CSimpleTransactionType               supported
D: IOI2CDDCciReplyTransactionType           supported
D: IOI2CCombinedTransactionType             supported
D: IOI2CDisplayPortNativeTransactionType    supported

D: IOI2CTransactionTypes: 0x1f (31)
D: IOI2CNoTransactionType                   supported
D: IOI2CSimpleTransactionType               supported
D: IOI2CDDCciReplyTransactionType           supported
D: IOI2CCombinedTransactionType             supported
D: IOI2CDisplayPortNativeTransactionType    supported

D: IOI2CTransactionTypes: 0x1f (31)
D: IOI2CNoTransactionType                   supported
D: IOI2CSimpleTransactionType               supported
D: IOI2CDDCciReplyTransactionType           supported
D: IOI2CCombinedTransactionType             supported
D: IOI2CDisplayPortNativeTransactionType    supported
E: No data after 10 tries!
2017-04-23 14:20:12.602 ddcctl[9710:1882694] E: DDC send command failed!
2017-04-23 14:20:12.602 ddcctl[9710:1882694] E: VCP control #16 (0x10) = current: 0, max: 0
```
