### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by therealmarv** [kfix/ddcctl#25]
Suggesting a good open source license... maybe MIT ?

**Comment by kfix** [comment]
Yeah, there's a few panels who have lifted my code, modified from that which was lifted from jontaylor/DDC-CI-Tools-for-OS-X, who selected GPLv3. LGPL or MIT would be more appropriate but I can't relicense that stuff.

**Comment by terinjokes** [comment]
@kfix Would you say this is GPLv3 then, since that's what jontaylor has?

**Comment by kfix** [comment]
IANAL, but yes
