### ISSUE TITLE
How to use UI with OSDisplay.app?

### ISSUE THREAD

**Issue by terabyte128** [kfix/ddcctl#27]
I can't figure out how to get OSDisplay.app... is it available online, or is it compiled with the application?

BTW, thanks for writing this, it works beautifully with my Dell U3415W.

**Comment by kfix** [comment]
it is at @Saman-VDR /OSDisplay.git. I have not used it myself.

Thanks for the note!

**Comment by kfix** [comment]
sorry, here : https://github.com/zulu-entertainment/OSDisplay

**Comment by terabyte128** [comment]
Thanks!
