### ISSUE TITLE
System freeze

### ISSUE THREAD

**Issue by nkgm** [kfix/ddcctl#3]
I'm trying this on a 2014 Mac Mini with a Lenovo L220 (over HDMI) and a Dell UP3214Q (monitor's Displayport connected to Mini's Thunderbolt port). Observations so far:

1. On the Lenovo, any attempt to change the brightness or contrast results in 100% regardless of the provided value. Trying to change the input source has no effect.

2. On the Dell, each run of the command has no effect, but sometimes it will freeze the entire system making a hard reset necessary. (system won't respond to any input, yet Spotify keeps playing)

Any ideas how to prevent the freeze?

**Comment by kfix** [comment]
Some monitors are simply dumb. There's no way to debug them.
Input and volume switching rarely works, usually only brightness and contrast is consistently implemented across brands.
I have used ddcctl successfully with a Lenovo LI2221s over HDMI.

ddcctl makes kernel-mode calls to twiddle DDC which is hardly ever done on Macs and probably not tested by Apple. So crashes can happen. I put in long delays between commands to minimize their occurrence. I'm not a kernel engineer and can't debug this for you.

Sorry for the delay.
