### ISSUE TITLE
DDC send command failed!

### ISSUE THREAD

**Issue by roddy20** [kfix/ddcctl#30]
D: NSScreen #724058892 (1600x1200 0°) 111.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: MY5468281HKL
I: got edid.name: DELL 2007FP
D: action: b: 25
D: setting VCP control #16 => 25

I can set Brightness, Reset, Color profiles OK, but I cannot read any value from the display

D: action: b: ?
D: querying VCP control: #16 =?
E: No data after 10 tries! 
E: DDC send command failed!
E: VCP control #16 (0x10) = current: 0, max: 0

can it be fixed? Thanks

**Comment by kfix** [comment]
closed by #31 : probably using a hackintosh -- this is explicitly unsupported.

Feel free to debug on your own, there is a `make debug` target in the Makefile.
`ddcctl -D` is an undocumented switch that will try to dump all DDC values.

**Comment by rdmasio** [comment]
Where can I find the hackintosh _explicitly unsupported_ statement? 
Please add that info to the readme.

**Comment by tjanson** [comment]
@rdmasio That's in the issue template. Feel free to open a PR ;)

**Comment by kfix** [comment]
I mean, everything is unsupported really?
I don't know how i can nicely make that clear to folks, but I'll try again in the README.
