### ISSUE TITLE
How to trigger OSDisplay?

### ISSUE THREAD

**Issue by dzg** [kfix/ddcctl#32]
This is great, thank you!

I built OSDisplay; it works from command line.

Then I tried `make CCFLAGS=-DOSD clean ddcctl`

But running a `ddcctl` command does not trigger a bezel display.

I also tried my own script that runs `ddcctl` and OSDisplay right after ... but then I have to wait for the OSDisplay 'delay' to complete before I can turn up the brightness. Is there a way to make it work like the native brightness, where you can trigger it multiple times in succession rapidly?

**Comment by dzg** [comment]
OK, I'm an idiot. Just saw the `-O` option.

**Comment by darkermatter** [comment]
Well, I'm an even bigger idiot because I'm using ```-O``` and it doesn't work.

I have OSDisplay.app in /Applications and can run it from the shell.

Any ideas?

**Comment by darkermatter** [comment]
Okay, I just read the code and it only supports brightness and contrast - I was trying with volume.

**Comment by kfix** [comment]
relates to #34 , OSDisplay integration need to be reworked.
