### ISSUE TITLE
Reading brightness doesn't work through USB-C to DP cable

### ISSUE THREAD

**Issue by DeboutSQ** [kfix/ddcctl#33]
Hello.

I'm using a Dell P2415Q with a MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports) on OS X 10.13.3 through a USB-C to DP cable.

Here are the outputs.

    $ ./ddcctl -d 1 -b ?
    2018-03-09 17:05:06.976 ddcctl[10727:3423095] D: NSScreen #724073921 (1920x1080 0°) HiDPI
    2018-03-09 17:05:06.976 ddcctl[10727:3423095] I: found 1 external display
    2018-03-09 17:05:06.976 ddcctl[10727:3423095] I: polling display 1's EDID
    
    Framebuffer: AppleIntelFramebuffer
     IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebuffer@1/display0/AppleDisplay
    VN:4268 PN:41150 SN:808800834 UN:1 IN:15107 Serial:

    2018-03-09 17:05:06.992 ddcctl[10727:3423095] I: got edid.serial: 3VV1478B05RB
    2018-03-09 17:05:06.992 ddcctl[10727:3423095] I: got edid.name: DELL P2415Q
    2018-03-09 17:05:06.992 ddcctl[10727:3423095] D: action: b: ?
    2018-03-09 17:05:06.992 ddcctl[10727:3423095] D: querying VCP control: #16 =?

    D: IOI2CTransactionTypes: 0x13 (19)
    D: IOI2CNoTransactionType                   supported 
    D: IOI2CSimpleTransactionType               supported 
    E: IOI2CDDCciReplyTransactionType           unsupported 
    E: IOI2CCombinedTransactionType             unsupported 
    D: IOI2CDisplayPortNativeTransactionType    supported

    Framebuffer: AppleIntelFramebuffer
    IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebuffer@1/display0/AppleDisplay
    VN:4268 PN:41150 SN:808800834 UN:1 IN:15887 Serial:

    D: IOI2CTransactionTypes: 0x13 (19)
    D: IOI2CNoTransactionType                   supported 
    D: IOI2CSimpleTransactionType               supported 
    E: IOI2CDDCciReplyTransactionType           unsupported 
    E: IOI2CCombinedTransactionType             unsupported 
    D: IOI2CDisplayPortNativeTransactionType    supported 

......repeat for 8 more times......

    E: No data after 10 tries! 
    2018-03-09 17:05:07.584 ddcctl[10727:3423095] E: DDC send command failed!
    2018-03-09 17:05:07.584 ddcctl[10727:3423095] E: VCP control #16 (0x10) = current: 0, max: 0

But when I tried this on a older MacBook Pro through Thunderbolt2(mDP) to DP on the same screen everything worked well.

Thank you.

**Comment by kfix** [comment]
I'm using Nekteck USB-C<>HDMI adapters and I have the same problem with my Dell monitor of similar vintage. My LG monitor reports brightness correctly.

I will have an AmazonBasics DP dongle to try with the Dell soonish.

**Comment by BartVB** [comment]
Related problem here. Have used this script without issue with a mini-DP/TB to DP cable between my BenQ SW320 monitor and mid-2014 15" MBP.

Recently switched to a 2018 15" MBT with a usb-c to DP cable (Choetech XCP-1801). Using ddcctrl works intermittently: https://gist.github.com/BartVB/07b8b408bb3ed4dab136c38fbde1b749

Debug build output: https://gist.github.com/BartVB/93dc9ec4f74e5bc5ceb0078134e6c6fa

Thanks a lot for creating and maintaining ddcctl! It's wonderful to be able to quickly adjust the monitor without using the monitor menu.

**Comment by BartVB** [comment]
Seems to fix it for me:

https://gist.github.com/BartVB/3ffc46c1acf72fde457681e20686dd40

Thanks!

**Comment by kfix** [comment]
Fixed by 3ba7c0f
