### ISSUE TITLE
Auto tracking feature of main display [improvement]

### ISSUE THREAD

**Issue by CatalinMustata** [kfix/ddcctl#37]
I'm currently working on adding an `auto mode` functionality that tracks the main laptop display and sets all the other displays to match.

On top of that, I've added an Xcode project and I'm looking at making this a menu bar application (plus some other features, like biasing). Considering these are quite large changes to the current codebase, would you want me to make a fork and develop a separate app or would you want to receive a pull request with the changes?

Cheers,
Cat

**Comment by stroborobo** [comment]
That's a cool idea! Btw there's a menu bar app already over here: https://github.com/the0neyouseek/MonitorControl

Not sure if this feature might be out of scope for this cli tool though, as it's rather stateless and you'd probably want to configure some things for a feature like this. Like smallest/highest common brightness, step factor maybe? Idk, just brainstorming.

**Comment by CatalinMustata** [comment]
Yeah, that was my thinking as well, that it's too much for CLI. So in the end I forked this and went ahead in building the application slightly separately from ddcctl (just using DDC.h/c and _some_ code from ddcctl.m). You can find it here: https://github.com/CatalinMustata/Lumos (haven't had time to change the description and readme just yet)

I've already implemented tracking mode and have found the following things:
- ddcctl very nicely ignores the Apple displays when listing (which helps)
- there's a different way to get and control the built-in display, through IORegistry, so it's a good idea to treat it separately (no idea what happens with an iMac or an old Apple external display)
- the reference to the built-in display gets lost when you close the lid, so tracking mode fails to work after that. I probably need to hook up to some CoreGraphics display change notification (found one when I was researching) and redo all the mappings
- the laptop lid has a much wider brightness gamut than my 24" DELL. At first I'll hardcode a transfer function, but after that I'll add a preferences panel where you can set your own mapping (say 0 on the external is 40 on the macbook and 100 is 70 and make the transition linear/exponential)

**Comment by kfix** [comment]
hey @CatalinMustata, sorry I didn't get back to you. My life took a turn for the dramatic in April.

I really prefer the command-line to Xcode and would simply prefer a PR to turn ddcctl into a vendorable lib + tool that others could Carthage or CocoaPod (or whatever) into their Xcode projects for re-utilization.
