### ISSUE TITLE
Color preset?

### ISSUE THREAD

**Issue by nree** [kfix/ddcctl#39]
I'm curious, the README mentions color preset control, `ddcctl -h` doesn't show me an option to query or set this.

I imagine this is for monitors like mine that come with preset settings? For example "Default" , " Gaming", "Movie" etc.

So it would be possible to do something like, `ddcctl -preset Gaming` or something to switch to those settings.

**Comment by kfix** [comment]
Ddcctl cant guess or probe what controls your monitor supports. DDC codes' specifications are loosely implemented by manufacturers.

You can use the dump flag (-d) to enumerate all 255 ish codes and maybe identify your monitors profile switch (if any) and implement a cmdopt for it.
