### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by wise-rice** [kfix/ddcctl#4]
Hi there - I want to use your Program because "Brightnes Menulet by superduper crashes my machine.

But: I can't install your program.

heres what I did (did I even do the right thing?)

First I cloned your Git via Terminal. that works.

then I enter cd //Users/laptop/ddcctl/

I enter "make install"

and I recieve the following errors- what do the mean and how can I solve this problem ? :

Schlappy:ddcctl laptop$ make install
gcc -Wall -o ddcctl -lobjc -framework IOKit -framework AppKit -framework Foundation DDC.o ddcctl.m
In file included from ddcctl.m:20:
./DDC.h:87:5: warning: declaration does not declare anything
      [-Wmissing-declarations]
    union inputbitmap {
    ^
./DDC.h:185:13: warning: declaration does not declare anything
      [-Wmissing-declarations]
            union sync {
            ^
ddcctl.m:160:20: warning: missing terminating '"' character [-Winvalid-pp-token]
            MyLog(@"Usage:\n\
                   ^
ddcctl.m:160:19: error: unexpected '@' in program
            MyLog(@"Usage:\n\
                  ^
ddcctl.m:168:24: warning: missing terminating ' character [-Winvalid-pp-token]
----- Settings that don't always work -----
                       ^
ddcctl.m:178:38: warning: missing terminating '"' character [-Winvalid-pp-token]
 -X <NN>+ (increases setting X by NN)");
                                     ^
ddcctl.m:182:2: error: expected '}'
}
 ^
ddcctl.m:60:1: note: to match this '{'
{
^
5 warnings and 2 errors generated.
make: *** [ddcctl] Error 1

**Comment by kfix** [comment]
This might crash your machine too!

**Comment by wise-rice** [comment]
Im Sorry to hear that...
It must be because of my onboard HD4000 graphics...

If there was a Script to disconnect the monitor before running the app- everything would be fine

**Comment by kfix** [comment]
What kind of machine do you have?
#1 indicated that some stock Macs can have problems.
FWIW, my 2013/14 MBP works fine w/ NVIDIA GT750M

**Comment by wise-rice** [comment]
A 13" mid-2012 macbook pro with onboard intel hd4000 graphics and osx 10.10.5

**Comment by wise-rice** [comment]
Oh and I use a Dell U2515H.

Do you know What I did wrong  in the terminal? Does it not install because of osx 10.10.5 or is it my lack of knowledge about coding ?

Whatever it is, 
Thank you for you qick reply in the first place! It is rare, that people actually care about others problems

**Comment by Kalvin126** [comment]
I just got a DELL U2515H and have tested it to work.

Check out my fork of the BrightnessMenulet
https://github.com/Kalvin126/BrightnessMenulet
