### ISSUE TITLE
Does not work via USB 3.0 input?

### ISSUE THREAD

**Issue by mfeng9** [kfix/ddcctl#48]
I am trying this program on out ASUS MB169B+ Portable Display which is powered and has data transferred from a USB 3.0 port, and it is showing me the message below (on Macbook Pro):

```bash
D: NSScreen #339234107 (1080x1920 90°) 141.00 DPI
I: found 1 external display
I: polling display 1's EDID
E: Failed to poll display!
```

I read the README.md and I could not find a USB 3.0 option from the list of supported inputs. I am wondering if USB 3.0 input is supported by this program or not. If not, is there any chance to add the support for USB 3.0 input? 

Really appreciate the incredible effort to support this program!

**Comment by kfix** [comment]
From this [post](https://askubuntu.com/questions/744364/displaylink-asus-mb168b-issues) i suspect the monitor you have is a (EVDI)[https://github.com/DisplayLink/evdi] device, which is a GPU & display combo, not just a plain DisplayLink monitor on a DP/Thunderbolt port.

There appears to be some concept of an EDID block in the EVDI spec to inform the OS of overall dimensions and clocking of your screen, but I don't see an analogue to the I2C control channel that DDC commands are carried on. The asus "EzLink" driver & app (Windows only!) seems to do some thing special to set "auto-bright" on and off, and its not DDC.
