### ISSUE TITLE
OS freezes when using relative setting

### ISSUE THREAD

**Issue by adeg** [kfix/ddcctl#5]
When running ddcctl to increase/decrease brightness/contrast (relative setting) on OS X 10.11 Beta (15A278b), MacBook Pro w/ Retina, Dell U3415W connected via DisplayPort, the system would stop processing input from keyboard and mouse. Setting brightness/contrast to a specified value worked.

Checking the repository which was the source of some of the code found this issue: https://github.com/jontaylor/DDC-CI-Tools-for-OS-X/issues/4

Applying the same workaround helped in ddcctl case as well. After commenting out the following line (https://github.com/kfix/ddcctl/blob/master/DDC.c#L183) and recompiling, I am able to use relative setting.

I would have submitted a Pull Request, but not sure if minReplyDelay could simply be discarded or should be lowered.

**Comment by kfix** [comment]
[Quoth](http://www.tonymacx86.com/graphics/90077-controlling-your-monitor-osx-ddc-panel-7.html#post831492) the original author:

>If you can write but have trouble reading, it's possible the read delay isn't long enough. 
...
>The default value used by DDC Panel is based on what should mathematically be the latency of the connection, but it's not precise; even long cables can disrupt it. I haven't found a good, performant value so far.

**Comment by adeg** [comment]
Hmm, I could have agreed with that if increasing would have been the solution. Contrary to that, _removing minReplyDelay_ did help. So maybe this parameter should not be enforced? Anyway, this is just guessing from my side, since Apple provided documentation on this component is pretty vague, and I could not find other sources to read more on this.

**Comment by wise-rice** [comment]
Is there a chance everything gets better with the new OSX end of the month?

**Comment by adeg** [comment]
@wise-rice, I have installed OS X 10.11 El Capitan GM (which is likely to be promoted to release if no major bugs are discovered) and am having the same issues. So it is unlikely that things will get better by themselves.

I have been doing some testing with the above workaround (minReplyDelay commented out) and see a different type of issue when using relative setting: set command sent after get often fails. I will try testing it with a very small _minReplyDelay_.

**Comment by kfix** [comment]
@adeg Let me know what ends up working for you. I'm going to make this tunable from cmdline so that edge cases like yours (zero-delay necessary) can be worked-around.

**Comment by kfix** [comment]
mitigated by new tunable with 3a58530
