### ISSUE TITLE
Read current display input

### ISSUE THREAD

**Issue by ParhamG** [kfix/ddcctl#59]
I am using this on a Mac Mini 2018 with a Dell P2715Q to switch between the inputs (HDMI-1 and DP-1) which works great! But, I'd like to be able to toggle between these two ports using a shortcut or something and I was wondering if it is possible to read the current input? so based on the current state switch to the other one?

Running `ddcctl -d 1 -i ?` gives me:
```
D: NSScreen #722475277 (3840x2160 0°) 163.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: 54KKD75RA56L
I: got edid.name: DELL P2715Q
D: action: i: ?
D: querying VCP control: #96 =?
E: No data after 10 tries! 
E: DDC send command failed!
E: VCP control #96 (0x60) = current: 0, max: 0
```

The display is connected to mac using a USB-C to DP cable.

**Comment by tomtastic** [comment]
If your monitor doesn't allow reading the value, perhaps touch a state file somewhere with the current value, and switch based on that ?

**Comment by kfix** [comment]
not all monitors support polling input value - I'd wager the majority don't

**Comment by gokceneraslan** [comment]
Make sure DDC is enabled (it's sometimes disabled by default in Dell P2715Q for whatever reason)

![image](https://user-images.githubusercontent.com/1140359/130479377-3852e506-69e1-4435-a924-5cc5de2827f9.png)
