### ISSUE TITLE
Usage w/ eGPU?

### ISSUE THREAD

**Issue by kevinschaich** [kfix/ddcctl#60]
Build:
Mac Mini (Late 2018)
MacOS Catalina 10.15.3
Razer X Core eGPU w/ AMD Radeon VII (Connected via USB-C to USB-C)
Dell U3219Q (Connected via Displayport - Displayport through Razer Core X)

I've tried every permutation I can think of of setting brightness to no avail:

```bash
~/ddcctl master
❯ ./ddcctl -d 1 -b 50
D: NSScreen #724041876 (3008x1692 0°) HiDPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: 8QLNWP2
I: got edid.name: DELL U3219Q
D: action: b: 50
D: setting VCP control #16 => 50

❯ ./ddcctl -d 1 -i 15 -b 50
D: NSScreen #724041876 (3008x1692 0°) HiDPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: 8QLNWP2
I: got edid.name: DELL U3219Q
D: action: i: 15
D: setting VCP control #96 => 15
D: action: b: 50
D: setting VCP control #16 => 50

~/ddcctl master
❯ ./ddcctl -d 1 -i 16 -b 50
D: NSScreen #724041876 (3008x1692 0°) HiDPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: 8QLNWP2
I: got edid.name: DELL U3219Q
D: action: i: 16
D: setting VCP control #96 => 16
D: action: b: 50
D: setting VCP control #16 => 50
```

Nothing seems to work. It works perfectly when my computer is connected directly to the monitor via USB-C:

```
~/ddcctl master
❯ ./ddcctl -d 1 -b 100
D: NSScreen #724042060 (3008x1692 0°) HiDPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: 8QLNWP2
I: got edid.name: DELL U3219Q
D: action: b: 100
D: setting VCP control #16 => 100
```

**Comment by sn0wyfall** [comment]
Isn't this just an issue with the eGPU not supporting DDC commands? I bought a USB C dock and it didn't support DDC though the HDMI port, but I had a cheaper hub that did.

**Comment by kfix** [comment]
I don't have an eGPU enclose so can't really dig into this myself.
closing due to that and lack of activity.

**Comment by varenc** [comment]
I have an eGPU and ddctl still works fine.  Monitor is connected to the eGPU over DisplayPort though not HDMI
