### ISSUE TITLE
Set DDCRead kDDCMinReplyDelay value but macOS crash

### ISSUE THREAD

**Issue by comie1027** [kfix/ddcctl#68]
Monitor: DELL U3219Q
Platform: MacbookPro13 2018 with macOS Catalina 10.15.5
IDE: XCode 11.5 using objectiveC
I try to get Capability String (6E 51 83 F3..) by DDCRead API. It takes 18 seconds to get the result. 
Try to set different kDDCMinReplyDelay value. Only 0, 10, 1000 works. Other kDDCMinReplyDelay value will result in macOS crash.
It might be the IOKit limitation. Or is there other way to shorten getting capabilitilty string time?

**Comment by kfix** [comment]
sorry, no way to change at runtime yet: https://github.com/kfix/ddcctl/commit/02dcf6c9ae77783f50a9948a829dee6865131ef6#diff-b16659e6a940204d49d5f22dbe3b0812R219

patches welcome
