### ISSUE TITLE
Apple Silicon/Developer Transition Kit support?

### ISSUE THREAD

**Issue by julianschiavo** [kfix/ddcctl#70]
Is it known if `ddcctl` works on Apple Silicon/Developer Transition Kit? I'm not sure if it's my monitor, my cable, or the DTK considering that it has an ARM Apple chip.

**Platform:** Developer Transition Kit
**OS:** macOS Big Sur Beta 3
**Monitor:** Dell P2421D
**Connection:** DisplayPort cable with USB-C adapter plugged into Mac

**Output:**
```bash
$ make intel   
rm -f *.o ddcctl
cc -Wall -Wno-unused-variable -DkDDCMinReplyDelay=1 -c -o DDC.o DDC.c
cc -Wall -Wno-unused-variable -DkDDCMinReplyDelay=1 -o ddcctl -lobjc -framework IOKit -framework AppKit -framework Foundation DDC.o ddcctl.m

$ ./ddcctl -d 1
D: NSScreen #2 (2560x1440 0°) 123.00 DPI
I: found 1 external display
I: polling display 1's EDID
E: Failed to poll display!
```

**Comment by kfix** [comment]
That's unfortunate, but I wouldn't be shocked that an ARMbook's macOS stubs out more of the the bitrotted Darwin IOKit APIs that `ddcctl` depends on.
