### ISSUE TITLE
Makefile does not support CLI to add -DDEBUG

### ISSUE THREAD

**Issue by gherlein** [kfix/ddcctl#77]
Adding in the force of amd|intel|nvidia broke the ability to specify a debug build.

➜  ddcctl git:(fix-makefile) ✗ make debug intel
rm -f *.o ddcctl
cc -Wall -Wno-unused-variable -DDEBUG -c -o DDC.o DDC.c
DDC.c:20:1: error: static_assert failed "must build with `make (amd|intel|nvidia)`"
_Static_assert (0, "must build with `make (amd|intel|nvidia)`");
^               ~
DDC.c:218:51: error: use of undeclared identifier 'kDDCMinReplyDelay'
        request.minReplyDelay                   = kDDCMinReplyDelay * kNanosecondScale;
                                                  ^
2 errors generated.
make: *** [DDC.o] Error 1

I'm pondering how to fix this, possibly using $(MAKECMDGOALS) or something but the solution is not jumping to mind.  So logging this here in the meantime.

**Comment by kfix** [comment]
yeah, #83 reports the same.

**Comment by kfix** [comment]
PR #84 uses the goals var, will give it a try.

**Comment by jnooree** [comment]
> PR #84 uses the goals var, will give it a try.

I've updated it to work with other targets, now it supports something like `make debug amd`.
