### ISSUE TITLE
Dell D6000 USB-C dock - Cannot control monitors attached to DP

### ISSUE THREAD

**Issue by JBFUK** [kfix/ddcctl#83]
Dell D6000 USB-C dock connected to MacBook Pro running latest version of OS X.  Latest version of ddcctl compiled with 'intel' option.  I have 3x Dell S2721DGF monitors connected, one (#1) connects to the D6000 HDMI output, the other two (#2/#3) are connected to the D6000 DP outputs.  Display manager works when bootcamping in to Windoze.

The application works perfectly with display #1 - connected to HDMI.

When trying to manipulate display #2 or #3 I get the following:

```
jbf@JBFMBP ddcctl % ./ddcctl -d 2 -b 50                    
D: NSScreen #722486414 (2560x1440 0°) 109.00 DPI
D: NSScreen #722486548 (2560x1440 0°) 109.00 DPI
D: NSScreen #722489109 (2560x1440 0°) 109.00 DPI
I: found 3 external displays
I: polling display 2's EDID
E: Failed to poll display!

```

I didn't seem to be able to compile with the debug option, when I tried it make complained about only wanting a video card type option supplied.  This is probably me not knowing how to supply the debug option correctly.  I have tried "make debug", "make intel CCFLAGS=-DDEBUG" and "make CCFLAGS=-DDEBUG intel' but all give the error -

```
DDC.c:20:1: error: static_assert failed "must build with
      `make (amd|intel|nvidia)`"
```

I'm aware of Issue #17 - while I do have all three displays the same type, the output suggests they have all been detected independently and I do not get the same error documented in that issue, so do not believe that is the problem.

Please let me know if I can provide any other information.

**Comment by kfix** [comment]
You might have the issue in #17, still.
My 2015 Dell U2415 does have a unique-ish serial number.
But I'm not sure how consistent they are with that across models.

that does seem weird that the build assert isn't working when you add the debug flag.
There's a PR that adds an Xcode project, so maybe that will give better results...

**Comment by JBFUK** [comment]
Possible.  I presume I'm not supplying the debug compile options correctly?

**Comment by kfix** [comment]
`make debug` was recently fixed

gonna close due to age of ticket.
its quite possible things still won't work as the are noted issues with USB-C docks.

I don't have one and they are a pandemic-constrained supply item so I won't be getting one anytime soon...
