### ISSUE TITLE
Monitor physical buttons no longer work after running ddctl command with -p flag

### ISSUE THREAD

**Issue by lirenyeo** [kfix/ddcctl#89]
Found this great tool and was using it for brightness adjustment for half a day, until I decided to try out the `-p` and `-m` flags, now upon **pressing any physical button on my monitor, it will simply restart itself** (go blank, then automatically detect input source and back to normal).

Previously with all the brightness adjustments this problem did not occur, until I started to try running:
`./ddcctl -d 1 -p 1` (did it 3 times with value 1, 2 and 3, each time it goes blank, then back to normal)
then I also did `./ddcctl -d 1 -m 1`, also tried with value 2.

I'm not sure exactly which of the above commands caused the issue.

I have tried plug it into my windows and use softMCCS to restore it to factory default but the problem persist.
Is there anyway to hard reset a monitor?

Monitor brand/model: [Mi Curved Gaming Monitor 34 inch](https://www.mi.com/my/monitor34/)

**Comment by kfix** [comment]
Oh dear, that's awful.
This is the first I've heard of a monitor getting bricked from DDC commands!

[It does not look like it has a host USB port](https://www.mi.com/global/monitor34/specs/) to supply it a firmware update, in an attempt to clear its settings.

Did you try using all of the HDMI & DP ports?

I'm afraid the only recourse here is to open it up and use an IC clip on whatever flash chip the settings are being saved to and try to find the right value to hack.

**Comment by kfix** [comment]
I'm going to revise that `Settings that don't always work` language in the --help to indicate that these commands are potentially device altering.

**Comment by kfix** [comment]
Next guess is to unplug the monitor's power for a long time to see if some volatile flash will unstick.

**Comment by lirenyeo** [comment]
> Next guess is to unplug the monitor's power for a long time to see if some volatile flash will unstick.

I will try this and also write to Xiaomi to see if there is anyway to do a firmware update or re-flash the memory.
Regardless, thank you for your response. I will update here if I manage to find any fix.

**Comment by nk9** [comment]
Any update on this? I'd like some confidence that I won't mess up my hardware by playing with the settings/hacking on a fork.

**Comment by kfix** [comment]
Sorry, have not heard of any other instances or resolution to this one.

Going to close as there is a feature issue opened to implement feature detection, in an attempt to prevent bricking.

**Comment by ramsaylanier** [comment]
I have had the same thing happen to me just now by using the `-p` flag. I had no warning or any type of messaging saying that this was even possible, and yet this issue is still closed?!

**Comment by Crazor** [comment]
On my LG 27UL650-W, I encounter something that may be related, although it's reversible. When I use -p with any parameter (1-5), the display does indeed turn off (still detected by macOS). However, there is no way other than power cycling to wake it back up! Could this be the display's firmware crashing? How would I debug this?

**Comment by kfix** [comment]
Sorry @Crazor, can't you help you there. That sounds like a plausible theory though.

If `-p` is this destructive (3 reports so far) then I'm going to remove it and tell future flag adding PRs to eff off.
