### ISSUE TITLE
[Feature Request] USB input switching

### ISSUE THREAD

**Issue by nk9** [kfix/ddcctl#94]
I have a Dell U3219Q which has a built-in KVM. It's possible to set the on-screen hardware buttons to switch USB inputs by pressing one of the configurable keys twice: set the "USB Select Switch" as the "Shortcut Key 1" in the "Personalize" section of the OSM.

But I'd really like to be able to do this from the command line so I can set a script to run when I press a key on my keyboard. That way, I won't have to reach up and touch the monitor. I'm hoping this setting is configurable via DDC. I'm happy to attempt to hack it myself, though I haven't done anything with IOKit or CGDisplay before. Any pointers on where to look?

**Comment by epilande** [comment]
@nk9 I'm looking for the exact same thing, were you able to find a solution for this?

**Comment by JTCodeDev** [comment]
Same here, following. If I can get some time I might try to figure out the code.

**Comment by kfix** [comment]
Vendor specific features is not on agenda for future features, sorry. See the latest README.
it has enough problems with "standard" things, there's no way I can support this without having the hardware to test it.
