### ISSUE TITLE
How to...?

### ISSUE THREAD

**Issue by btp2102** [kfix/ddcctl#95]
Hi, I am completely new to all of this. I'm trying to figure out how to use this script to control the brightness of my LG display, connected to an M1 MacMini. I've downloaded Alfred but have never used that either. Anyone able to help a dummy?

**Comment by codeHatcher** [comment]
I think you'll have a hard time getting a response to such a question on here. I also have a m1 mac and happen to be looking around but I think there isn't proper support for the display settings control from an m1 mac.

**Comment by kfix** [comment]
yes, I would subscribe to existing issue #86 
support for M1 has not been added yet but it (recently) seems to be possible, so perhaps it will be closed soon.
