### ISSUE TITLE
ddccdl on iMac detects 0 displays

### ISSUE THREAD

**Issue by HmACK666** [kfix/ddcctl#98]
I'm excited to see an active project dealing with command line controls for displays on macOS.
I use https://github.com/nriley/brightness to retrieve & set brightness in a lab of iMacs (Retina 5K, 27-inch, 2017).
While this tool works well on my Mac Pro (5,1) with two Apple Cinema Displays, when run on one of the iMacs I get:
I: found 0 external display

Just wondering if there are shortcomings with iMacs displays that would prevent this tool ever working?

**Comment by kfix** [comment]
the iMac screen is internal and doesn't use DDC, so `ddcctl` doesn't support it.
Same for MacBook screens.

I guess you need to use both tools? I know that sounds weird, but they both are using two very different and finnicky APIs that Apple semi-supports.
